language: go
sudo: required
env:
  global:
  - CHANGE_MINIKUBE_NONE_USER=true
  - KUBERNETES_VERSION=v1.9.0
  - MINIKUBE_VERSION=v0.25.0
  - HELM_VERSION=v2.8.0
go:
- 1.9.x
- master
services:
- docker
matrix:
  fast_finish: true
  allow_failures:
  - go: master
before_install:
- sudo apt-get update
- sudo apt-get -y install python3 python3-pip
- make install-go-deps
- sudo make install-python-deps
- make pull-linters
install:
- "./test/scripts/nsenter.sh"
# Installing Minikube. Taken from https://kinvolk.io/blog/2017/10/running-kubernetes-on-travis-ci-with-minikube/
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBERNETES_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- curl -LO https://storage.googleapis.com/kubernetes-helm/helm-$HELM_VERSION-linux-amd64.tar.gz && tar -xzf helm-$HELM_VERSION-linux-amd64.tar.gz && sudo mv linux-amd64/helm /usr/local/bin/ && rm -rf linux-amd64
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBE_VERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
- sudo minikube start --vm-driver=none --kubernetes-version=$KUBERNETES_VERSION
- minikube update-context
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
- kubectl create -f test/data/crd.yml
- kubectl get crd
- dep ensure
script:
- make lint
- make test
- make -j 3 build-cross
- make docker-build-test
- make LOSTROMOS_IP_AND_PORT=`minikube service lostromos --url | cut -c 8-` integration-tests
- kubectl logs lostromos
- make coverage
after_script:
- "./out/lostromos-linux-am64 version"
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: Em13Oe/xI6D7iZbt1KIy7jx1pvBLX0KGcBOTk1lN3vCLh+TcEQI02KENkFfM7diuEG3djhumohjOytiFLSnoR7fdX3hVe+D0jBZqWki13tHB8TnOPTG3zKtrZjjwRPFGYM4WRWWs3TwnxZU0ji+5xB2JR3rVg8ESZUniyTg6KbvENui0Y9EbQzWb/+Uee3ZVidllxzw2j9FBABqpvmAtEk9a2wQbpShyMc4dSzwicdNnhMFCvf8uj3bOY+nAm3dSkYScPVYwNEVWZHSo9c1qgCibGYPu9NNX5ARwDz4pwUi0TI11oxz+iiWAZMbjE+m0fpp3E8O2RUNConzjnyoZlz9W6hFpTKsjIh1kfXrGe89mIzLQuM6wVfM1QrQxMH48TuaNsohtlyGQrJXunRpoYnp7hdMCobQQomUO0Yc1yvcEznEAi0oC82a6deq+g/H86fqNaXkyE/bbiXHh9d3GoFl+GBTyTdj4xy74j7hSYAdc0MFwDidZ6Wgr+BPqcCYze8H0naO5pZWmyLDfJrArYHNbNLWSodwXNhW43EFPNp5K5EkcnW0qpfORj2jACKYl0xOi1P1ZPMHWo0BMP6RdCZ4gUWRwX93X7BQVXjSYSC+yCU8fh+Epl4Wh6lJaGQFt8MDvvIK66CqAWM4rnQvNi1cyjmFipfEDH3Ez51drVv4=
  file_glob: true
  file: out/lostromos-*
  skip_cleanup: true
  on:
    repo: wpengine/lostromos
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.9\.[0-9]+$
