language: go
sudo: required
go:
- 1.9.x
- master
services:
- docker
matrix:
  fast_finish: true
  allow_failures:
  - go: master
before_install:
- sudo apt-get update
- sudo apt-get -y install python3 python3-pip
- make install-deps
- make pull-linters
install:
- "./test/scripts/install_minikube.sh"
- kubectl create -f test/data/crd.yml
- kubectl get crd
- dep ensure
- sudo pip3 install -r ./requirements.txt
script:
- make lint
- make test
- make build-cross
- make docker-build-test
- make LOSTROMOS_IP_AND_PORT=`minikube service lostromos --url | cut -c 8-` integration-tests
- kubectl logs lostromos
- make coverage
after_script:
- "./out/lostromos-linux-am64 version"
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: DIdFU9uOKwr5mDaSnVuKEIjotod8rSrWvKa3pCDyusM7bEGQ64drdbkhDSCLMk/oX6cFf6v57OoQJMVn3xPL04ou18v5wGT/WxA502yPme5VhkK5+TiRmrmkCPu3T40bI+EXQWaYi4lq9VehBoDiE8tOCvSXbm1RH+4StTQOLgZqRgMvZ4BgyUo0z5kZBTlfiuxUEpkofESHZ8u6jRyv2yCeDpnqJHEkqB2EfPLxc4sYjeqFcExs/BQR1BiUjlz99sCSEdi/hTjwJ2B7gQMPt3BT7LVpOiX0j1Qa5b6VtJrDfMS0gbcBXuczpaAYkofEWR0aYq+VaCKsWEOf1/CnWqbumgwwscU+6SbvEUDQiIN6Oz9nUrvN/Wr/+zIQUgMxtr2+T1hkNFakjdeXZ7Dg0R/O++/LDX3XtqJJ+xh2M4tUr5phTomJwPv0/StJD0sy5n2jRpcLxxjXF7kWMkKoMjW5xqS1eIo1yUS1JfCj5zFXFghIgbsMh30duvgD+/N4h7Y+5zZoxapjevMoCjlu6IN/lhvzKopI0ZGHRsUEE9SFPaFthwwj3Aqn3SkyqeiH/CzSyREahnSTiPNuyPpdY3rHi8JcU4IzAzOIwJ2v8timzI8gg9N3KmOMWfLYoVs7c1WDWnb0Nv/Vvu1C/RKPaG5Iabzn+rLMYjWNWJ5ivbs=
  file_glob: true
  file: out/lostromos-*
  skip_cleanup: true
  on:
    repo: wpengine/lostromos
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.9\.[0-9]+$
